### ISSUE TITLE
Gradle project syncエラー: com.tapia.mji:tapialib:1.0.0が見つからない

### ISSUE THREAD

**Issue by tsakama** [MJIrobotics/Tapia-sdk#1]
Gradleのプロジェクト同期を行うと、
Error:(35, 13) Failed to resolve: com.tapia.mji:tapialib:1.0.0
というエラーが発生しています。

依存しているライブラリtapialibが見つけられないとのことですが、何が原因として考えられますでしょうか？
TOSチュートリアルの「2. TAPIA SDKライブラリの実装」に従い、レポジトリログインID/PW、SDK認証コードを入力したところです。

**Comment by MJIrobotics** [comment]
tsakama様
MJIのSDK担当です。

ご登録いただきましたアカウントのアクティベート状況を確認しましたが正常にアクティベートされておりました。

下記の項目をご確認ください。
１．sdk_username及びsdk_passwordにはダブルクオーテーションで囲む必要がありません。
２．インターネットに接続されている。
３．http://tos.mjirobotics.co.jp:8081/artifactory/tapia-sdk/　にアクセスできる。

以上の3項目をご確認おねがいします。

**Comment by tsakama** [comment]
１．のダブルクオーテーションで囲んでいるのが原因でした。失礼しました。
文字列なのでうっかり囲んでしまいました。
