### ISSUE TITLE
TAPIAがUSBデバイスとして認識されない

### ISSUE THREAD

**Issue by satotakehirohack** [MJIrobotics/Tapia-sdk#13]
SDK版TAPIAをPC（Mac, Windows）をmicro USBで接続しようとしているのですが認識しません。

① android端末は認識されます。
② TAPIAのデバックモードはONになっていることを確認しています。
③ TAPIAではUSB接続設定（MTP接続の設定）の項目がないため設定していません。

ご教示よろしくお願いします。

**Comment by TakakoKubo** [comment]
2点確認させてください。
以下確認をしていただけないでしょうか。
確認①　USBドライバのインストールは完了していますか?
確認②　USBドライバのインストールが完了している場合、「SelectDeploymentTaget」ウィンドウで「タピアのデバイス」は選択していますか?
ご確認のほどお願い申し上げます。
引き続き質問ありましたらご連絡くださいますようお願いいたします。

**Comment by satotakehirohack** [comment]
本件何度かアダプタを抜き差ししたり、TAPIA側で認証デバイスの履歴を消去したりするなどすると接続されました。100%認識されるとまではいかないものの、接続されることが判明したため様子を見てみます。
ありがとうございます。
※Mac OSのためUSBドライバは不要との認識です。

**Comment by TakakoKubo** [comment]
様子を見るとのことでしたが、その後の接続はいかがでしょうか。
もしも不具合が続くようでしたら連絡くださいますようお願いいたします。本件は一旦クローズさせていただきます。
