### ISSUE TITLE
【解決】SampleコードのTalk機能が動かない

### ISSUE THREAD

**Issue by satotakehirohack** [MJIrobotics/Tapia-sdk#14]
SampleコードのTalk機能が動かなかったのですが、
AndroidManifest.xmlに
<activity android:configChanges="locale" android:screenOrientation="landscape" android:name=".Activities.TalkActivity" />
を追加したら動きました。

**Comment by TakakoKubo** [comment]
本件一旦クローズとさせていただきます。また何がありましたら連絡ください。
