### ISSUE TITLE
タピアの会話制限について

### ISSUE THREAD

**Issue by s-kawabata** [MJIrobotics/Tapia-sdk#22]
お世話になっております。

タピアで動作確認中に以下のメッセージが表示されました。
Maximum Daily Request reached
こちらはタピアとの会話回数が規定回数を超えた場合に表示されると認識しています。
しかし、現在開発中のタピアでは音声認識機能は使用しておらず、
音声関連の処理としては固定の文字列を渡してタピアに話させるという処理のみ実装しております。
タピアに固定の文字列を話せさせるだけでも会話回数としてカウントされてしまうのでしょうか。

以上、よろしくお願いいたします。

**Comment by MJIrobotics** [comment]
お世話になっております。
Maximum Daily Request reachedですが、コメントいただいきました通り規定回数を超えた場合に表示されます。
ソースコードにsttProvider.listen();が入っている場合、周囲の音をタピアが拾い聞き取りを開始してしまう為、ソースコードにsttProvider.listen();の記入があるのではないかと推測いたしますがいかがでしょうか。一度確認していただけますようお願いいたします。解決しない等ありしたらログを確認したいのでと設定しているメールアドレスをお教えていただけないでしょうか。それではどうぞよろしくお願いいたします。

**Comment by s-kawabata** [comment]
お世話になっております。
確認したところsttProvider.listen();はソースコードに入っていません。
ただ、タピアに話させる時にask関数を使用していることがわかり、該当箇所をsay関数に変更して様子を見ているところです。
ask関数を使用すると会話とカウントされるのでしょうか。

**Comment by MJIrobotics** [comment]
お世話になっております。
ask関数は引数にsttを含んでいる為カウントされてしまいますので、ご連絡いただきました通りsay関数を使用する事をお勧め致します。どうぞよろしくお願いいたします。
