### ISSUE TITLE
Failed to resolve: com.tapia.mji:tapialib:1.0.9

### ISSUE THREAD

**Issue by firdausmaulan** [MJIrobotics/Tapia-sdk#24]
I got this error when sync gradle
I already setup sdk_username & sdk_password on gradle.properties
also setup license_key on manifest

**Comment by firdausmaulan** [comment]
solved.
it caused by wrong sdk_password.
I'm not from Japan, so, I use google translate but I got mistranslation password (space added between char & number)

**Comment by MJIrobotics** [comment]
Thank you so much for your setup.
If you have any other questions,please fell free to ask.
