### ISSUE TITLE
TAPIAが音のする方を向かない

### ISSUE THREAD

**Issue by katy802mtnt** [MJIrobotics/Tapia-sdk#28]
お世話になっております。

サンプルコードの「11. 音のする方向に回転する」（https://tos.mjirobotics.co.jp/sdk/manual/CodeSample_11）
に関して質問があります。

サンプルコードを実装し実機で試したところ、音源の位置を正しく推定できずに毎回同じ方向を向いてしまいます。
音声の認識はおそらくできている（「はい何でしょうか」「はい、こっちかな」は正しいタイミングで話す）のですが
回転の方向が固定されます。

何十回に一度かは正しい音源の方向を向くため、音源の位置をセンシング出来ていないわけでもないのですが
動作が不安定です。
何が原因として考えられますでしょうか。

よろしくお願いいたします。

**Comment by mjikuwako** [comment]
pull request #29 にて一部対応を行なっております。  
以下のサンプルにて実装を行なっておりますので、実装方法についてはこちらメソッド内の実装をご参照ください。

https://github.com/MJIrobotics/Tapia-sdk/blob/4a9275e758addd444bdca3ae2e211ebd989457dd/tapia-sample/app/src/main/java/com/tapia/mji/demo/Activities/RotationActivity.java#L77

ただ、音源の位置を特定する機能は、ある程度機能はしますが、必ずしも正確な場所を音源の方向を特定できるというわけでありません。利用する場合は、以下の点に注意を行なって利用する必要があります

・音源の音の大きさ(音源の大きさによって、認識できない場合があります)
・周辺の音  (連続した環境音、別の音源等の影響を受ける場合があります。)
・周辺の環境 (音は反射するので周辺に反射する要素があるとその影響を受ける場合があります。)

音源定位は、通常の指向性マイクとは方向定位向けのマイクを利用しているため、音声認識の機能と必ずしも同等の認識能力を提供できるわけではありませんのでご注意いただく必要があります。

https://github.com/MJIrobotics/Tapia-sdk/blob/4a9275e758addd444bdca3ae2e211ebd989457dd/tapia-sample/app/src/main/java/com/tapia/mji/demo/Activities/RotationActivity.java#L83

また、音源定位を行なったタイミングでプリミティブな値を取得できるようになっておりますので、こちらをご活用ください。
