### ISSUE TITLE
TAPIAが動かない

### ISSUE THREAD

**Issue by IWAMIGINZI** [MJIrobotics/Tapia-sdk#4]
お世話になっております。

TAPIAを動かしたいのですが、サンプルコードの一行を追加しても動きません。
他に定義するものがいるのでしょうか？

いただいたコードの、SleepActivityに初期からある
TapiaRobot.rotate(activity, TapiaRobot.RotateOrientation.DOWN,200,null);
も動いていないようなのですが、引数などが問題でしょうか。

以上、ご回答よろしくお願い致します。

**Comment by MJIrobotics** [comment]
ご質問いただいた件について、回答させていただきます。

startActivity.javaの以下のコードをご確認くださいませ。

TapiaApp.ENABLE_ROBOT_FEATURE = true;

と記述されていますでしょうか。（値がtrueになっていますでしょうか）

このコードが、TapiaApp.ENABLE_ROBOT_FEATURE = false;
（値がfalseになっている）
と記述されていると、タピアが動作しません。

ご確認をお願いいたします。

**Comment by IWAMIGINZI** [comment]
falseになっていました。
trueにして解決しました。ありがとうございました。
