### ISSUE TITLE
TAPIAのvolume設定

### ISSUE THREAD

**Issue by IWAMIGINZI** [MJIrobotics/Tapia-sdk#5]
いつもお世話になっております。

TAPIA起動時の初期音量の設定をしたいと考えています。

サンプルソースStartActivity.javaにおいて
TapiaAudio.setVolume(this, TapiaAudio.getCurrent(), false);
この記述で音量設定をしているのでしょうか？
第2引数を変えても音量が変わらないです。

音量設定の仕方をお教えいただきたいです。

**Comment by MJIrobotics** [comment]
ご質問いただいた件に回答させていただきます。

>サンプルソースStartActivity.javaにおいて
>TapiaAudio.setVolume(this, TapiaAudio.getCurrent(), false);
>この記述で音量設定をしているのでしょうか？
おっしゃる通りです。

具体的には、第2引数を0～15の数値で記述くださいませ。
例．音量を10にしたい場合
TapiaAudio.setVolume(this, 10, false);

以上、ご確認をお願いいたします。

**Comment by IWAMIGINZI** [comment]
>具体的には、第2引数を0～15の数値で記述くださいませ。
第2引数を0～15の中で変更しても、音量が変わらないのですが。
以上、よろしくお願い致します。
