### ISSUE TITLE
TAPIAの話すスピード

### ISSUE THREAD

**Issue by IWAMIGINZI** [MJIrobotics/Tapia-sdk#7]
お世話になっております。

TAPIAの話すスピードを設定することはできるのでしょうか。

以上、よろしくお願い致します。

**Comment by MJIrobotics** [comment]
現在の最新ライブラリーのバージョンは　1.03ですが次回のバージョンアップで追加致します。
時期については追って公開させていただきます。

**Comment by MJIrobotics** [comment]
大変遅くなりました。SDKのバージョンアップを行い話すスピードを設定できるようにしました。
設定は以下の通りです。不明点ありましたら連絡下さい。
■バージョンアップ手順
①GradleScripts-build.gradle(Module:app)のdependenciesのcompileのバージョンを「'com.tapia.mji:tapialib:1.0.9'」　へ変更します。
②画面に右上に表示する「Sync Now」をクリックします。
■サンプルコード
https://tos.mjirobotics.co.jp/sdk/manual/CodeSample_7
