### ISSUE TITLE
TAPIAの傾きを取得する

### ISSUE THREAD

**Issue by IWAMIGINZI** [MJIrobotics/Tapia-sdk#9]
お世話になっております。

TAPIAの現在の傾き
（例. 右方向にx°回転している , x°上向いている など）
を取得することは可能でしょうか。

startSoundLocation();
で音の発生源の方向へ向きを変えることができたので、
「現在の傾きが変わった」ことをトリガーに処理を行いたいと考えています。

以上、よろしくお願い致します。

**Comment by MJIrobotics** [comment]
IWAMIGINZI様

上下、左右の位置を取得する方法はありません。
TAPIAにはサーボモーターを搭載していない為、位置を取得する方法がありません。
その為、TAPIA起動時に位置補正をする為に右に最大値回転してから中央値に戻す、
上に最大値に傾けて中央値に戻す作業をしています。

仮にSDKで位置指定をするのであれば、上記と同じような作業をする必要があります。
